### PR TITLE
Completed assignment

### PR DESCRIPTION
**Pull request by nisha-sharma**
Updated source code along with unit tests

### CODE REVIEW

**Comment by nisha-sharma** [comment]
Please review @VGeorSa @propattern

**Comment by nisha-sharma** [comment]
I have incorporated the review comments. Please review and share feedback.
@VGeorSa @propattern

**Comment by propattern** [comment]
Hi Nisha,

It seems that again the core requirement of the task is missing.  

These were the set of requirements that we expected to be completed:

screen shot 2018-09-11 at 12 03 11

If you look carefully, task two states that you need to `append` the data from remote to the JSON data that is already in the state.

which looks like:

```
[
  {
    "id": 4,
    "first_name": "Eve",
    "last_name": "Holt",
    "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/marcoramires/128.jpg"
  },
  {
    "id": 5,
    "first_name": "Charles",
    "last_name": "Morris",
    "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/stephenmoon/128.jpg"
  },
  {
    "id": 6,
    "first_name": "Tracey",
    "vlast_name": "Ramos",
    "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/bigmancho/128.jpg"
  }
]
```

When you merge the two data, you will notice that there are duplicates after merge (eve holt, id 4) is in both lists.

You then need to remove remove the duplicates based on the ID field.

Can you please apply the above change and resubmit.  

Cc @VGeorSa

**Comment by propattern** [comment]
Can you please run the master branch again and read the requirements CAREFULLY before this last and final attempt.  Thanks.

**Comment by propattern** [comment]
Reviewed and now closing this pull request. Feedback will be given through official channels. Thanks.

**Pull request closed without merging**
